apiVersion: v1
kind: Pod
metadata:
  name: models
spec:
  containers:
  - name: models
    image: ghcr.io/borncrusader/stanford-k8s-nextflow-demo-models:latest
    imagePullPolicy: Always
    volumeMounts:
    - name: data
      mountPath: /home/demouser/data
    ports:
    - containerPort: 5000
  volumes:
  - name: data
    hostPath:
      path: /data
      type: Directory
